using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Net.WebRequestMethods;

namespace DiamondTransaction.UI.Utilities
{
    public static class GridColumnFormat
    {
        public static List<ColumnFormat> DocHeaderColumnFormat = new List<ColumnFormat>
        {
            new ColumnFormat { Name = "DocHeaderID", HeaderText = "DocHeaderID", Width = 0 },
            new ColumnFormat { Name = "DocTypeID", HeaderText = "DocType", Width = 0 },
            new ColumnFormat { Name = "DocTypeDesc", HeaderText = "DocTypeDesc", Width = 0 },
            new ColumnFormat { Name = "DocID", HeaderText = "DocID", Width = 50 },
            new ColumnFormat { Name = "DocCode", HeaderText = "DocCode", Width = 80 },
            new ColumnFormat { Name = "DocAccountRefNo", HeaderText = "DocAccountRefNo", Width = 0 },
            new ColumnFormat { Name = "DocSubType", HeaderText = "SubType", Width = 60 },
            new ColumnFormat { Name = "DocStatus", HeaderText = "Status", Width = 50 },
            new ColumnFormat { Name = "DocDate", HeaderText = "DocDate", Width = 0 },
            new ColumnFormat { Name = "RefDocDate", HeaderText = "RefDocDate", Width = 0 },
            new ColumnFormat { Name = "RefDocDate2", HeaderText = "RefDocDate2", Width = 0 },
            new ColumnFormat { Name = "DueDate", HeaderText = "DueDate", Width = 0 },
            new ColumnFormat { Name = "LastUpdate", HeaderText = "LastUpdate", Width = 0 },
            new ColumnFormat { Name = "AccountCode", HeaderText = "AccountCode", Width = 80 },
            new ColumnFormat { Name = "AccountBranchCode", HeaderText = "AccountBranchCode", Width = 0 },
            new ColumnFormat { Name = "AccountName", HeaderText = "AccountName", Width = 0 },
            new ColumnFormat { Name = "AccountLongName", HeaderText = "AccountLongName", Width = 0 },
            new ColumnFormat { Name = "Currency", HeaderText = "Currency", Width = 60 },
            new ColumnFormat { Name = "VatCode", HeaderText = "VatCode", Width = 0 },
            new ColumnFormat { Name = "VatRate", HeaderText = "VatRate", Width = 0 },
            new ColumnFormat { Name = "PaymentTerm", HeaderText = "PaymentTerm", Width = 0 },
            new ColumnFormat { Name = "Loandays", HeaderText = "Loandays", Width = 0 },
            new ColumnFormat { Name = "Remark1", HeaderText = "Remark1", Width = 0 },
            new ColumnFormat { Name = "Remark2", HeaderText = "Remark2", Width = 0 },
            new ColumnFormat { Name = "InternalRemark", HeaderText = "InternalRemark", Width = 0 }, 
            new ColumnFormat { Name = "UserID", HeaderText = "UserID", Width = 0 },
            new ColumnFormat { Name = "Quantity", HeaderText = "Quantity", Width = 0 },
            new ColumnFormat { Name = "Weight", HeaderText = "Weight", Width = 50 },
            new ColumnFormat { Name = "MainLinesTotalPrice", HeaderText = "MainLinesTotalPrice", Width = 0 },
            new ColumnFormat { Name = "SecLinesTotalPrice", HeaderText = "SecLinesTotalPrice", Width = 0 },
            new ColumnFormat { Name = "DocLinesTotalPrice", HeaderText = "DocLinesTotalPrice", Width = 110 },
            new ColumnFormat { Name = "MainDiscountPrice", HeaderText = "MainDiscountPrice", Width = 0 },
            new ColumnFormat { Name = "SecDiscountPrice", HeaderText = "SecDiscountPrice", Width = 0 },
            new ColumnFormat { Name = "DocDiscountPrice", HeaderText = "DocDiscountPrice", Width = 0 },
            new ColumnFormat { Name = "DiscountPercent", HeaderText = "DiscountPercent", Width = 0 },
            new ColumnFormat { Name = "DiscountRemark", HeaderText = "DiscountRemark", Width = 0 },
            new ColumnFormat { Name = "MainSubTotalPrice", HeaderText = "MainSubTotalPrice", Width = 0 },
            new ColumnFormat { Name = "SecSubTotalPrice", HeaderText = "SecSubTotalPrice", Width = 0 },
            new ColumnFormat { Name = "DocSubTotalPrice", HeaderText = "DocSubTotalPrice", Width = 0 },
            new ColumnFormat { Name = "MainAdditionalPrice", HeaderText = "MainAdditionalPrice", Width = 0 },
            new ColumnFormat { Name = "SecAdditionalPrice", HeaderText = "SecAdditionalPrice", Width = 0 },
            new ColumnFormat { Name = "DocAdditionalPrice", HeaderText = "DocAdditionalPrice", Width = 0 },
            new ColumnFormat { Name = "AdditionalRemark", HeaderText = "AdditionalRemark", Width = 0 },
            new ColumnFormat { Name = "MainTaxPrice", HeaderText = "MainTaxPrice", Width = 0 },
            new ColumnFormat { Name = "SecTaxPrice", HeaderText = "SecTaxPrice", Width = 0 },
            new ColumnFormat { Name = "DocTaxPrice", HeaderText = "DocTaxPrice", Width = 80 },
            new ColumnFormat { Name = "MainGrandTotalPrice", HeaderText = "MainGrandTotalPrice", Width = 0 },
            new ColumnFormat { Name = "SecGrandTotalPrice", HeaderText = "SecGrandTotalPrice", Width = 0 },
            new ColumnFormat { Name = "DocGrandTotalPrice", HeaderText = "DocGrandTotalPrice", Width = 110 },
            new ColumnFormat { Name = "RateDocToMain", HeaderText = "RateDocToMain", Width = 0 },
            new ColumnFormat { Name = "RateDocToSec", HeaderText = "RateDocToSec", Width = 0 }
        };



        public static List<ColumnFormat> DocLineColumnFormat = new List<ColumnFormat>
        {
            new ColumnFormat { Name = "DocHeaderID", HeaderText = "DocHeaderID", Width = 0 },
            new ColumnFormat { Name = "DocLineID", HeaderText = "DocLineID", Width = 0 },
            new ColumnFormat { Name = "DocTypeID", HeaderText = "DocTypeID", Width = 0 },
            new ColumnFormat { Name = "DocTypeDesc", HeaderText = "DocTypeDesc", Width = 0 },
            new ColumnFormat { Name = "DocID", HeaderText = "DocID", Width = 55 },
            new ColumnFormat { Name = "DocLine", HeaderText = "Line", Width = 35 },
            new ColumnFormat { Name = "DocLineStatus", HeaderText = "Status", Width = 45 },
            new ColumnFormat { Name = "LotID", HeaderText = "LotID", Width = 65 },
            new ColumnFormat { Name = "ParentLotID", HeaderText = "ParentLotID", Width = 70 },
            new ColumnFormat { Name = "ItemID", HeaderText = "ItemID", Width = 0 },
            new ColumnFormat { Name = "LotName", HeaderText = "LotName", Width = 80 },
            new ColumnFormat { Name = "ParcelOrStone", HeaderText = "ParcelOrStone", Width = 0 },
            new ColumnFormat { Name = "HoldingType", HeaderText = "HoldingType", Width = 0 },
            new ColumnFormat { Name = "CertificateID", HeaderText = "CertificateID", Width = 80 },
            new ColumnFormat { Name = "Shape", HeaderText = "Shape", Width = 70 },
            new ColumnFormat { Name = "Size", HeaderText = "Size", Width = 60 },
            new ColumnFormat { Name = "Color", HeaderText = "Color", Width = 50 },
            new ColumnFormat { Name = "Clarity", HeaderText = "Clarity", Width = 60 },
            new ColumnFormat { Name = "Quantity", HeaderText = "Quantity", Width = 0 },
            new ColumnFormat { Name = "Weight", HeaderText = "Weight", Width = 60 },
            new ColumnFormat { Name = "WeightLoss", HeaderText = "WeightLoss", Width = 0 },
            new ColumnFormat { Name = "Cost", HeaderText = "Cost($)", Width = 70 },
            new ColumnFormat { Name = "TotalCost", HeaderText = "T.Cost($)", Width = 70 },
            new ColumnFormat { Name = "SecCost", HeaderText = "Cost(£)", Width = 0 },
            new ColumnFormat { Name = "SecTotalCost", HeaderText = "T.Cost(£)", Width = 0 },
            new ColumnFormat { Name = "Sale", HeaderText = "Sale", Width = 0 },
            new ColumnFormat { Name = "TotalSale", HeaderText = "T.Sale", Width = 0 },
            new ColumnFormat { Name = "SecSale", HeaderText = "Sale(£)", Width = 0 },
            new ColumnFormat { Name = "SecTotalSale", HeaderText = "T.Sale(£)", Width = 0 },
            new ColumnFormat { Name = "Additional", HeaderText = "Additional", Width = 0 },
            new ColumnFormat { Name = "TotalAdditional", HeaderText = "T.Additional", Width = 0 },
            new ColumnFormat { Name = "MainPrice", HeaderText = "MainPrice", Width = 70 },
            new ColumnFormat { Name = "TotalMainPrice", HeaderText = "T.MainPrice", Width = 85 },
            new ColumnFormat { Name = "SecPrice", HeaderText = "GBP Price", Width = 85 },
            new ColumnFormat { Name = "TotalSecPrice", HeaderText = "T.GBP Price", Width = 95 },
            new ColumnFormat { Name = "DocPrice", HeaderText = "DocPrice", Width = 70 },
            new ColumnFormat { Name = "TotalDocPrice", HeaderText = "T.DocPrice", Width = 85 },
            new ColumnFormat { Name = "RateDocToMain", HeaderText = "RateDocToMain", Width = 0 },
            new ColumnFormat { Name = "RateDocToSec", HeaderText = "RateDocToSec", Width = 0 },
            new ColumnFormat { Name = "List", HeaderText = "List", Width = 0 },
            new ColumnFormat { Name = "TotalList", HeaderText = "TotalList", Width = 0 },
            new ColumnFormat { Name = "ListCostDiscount", HeaderText = "CostDisc%", Width = 70 },
            new ColumnFormat { Name = "ListSaleDiscount", HeaderText = "ListSaleDiscount", Width = 0 },
            new ColumnFormat { Name = "ListMainDiscount", HeaderText = "ListMainDiscount", Width = 0 },
            new ColumnFormat { Name = "Remark", HeaderText = "Remark", Width = 0 },
            new ColumnFormat { Name = "OutList", HeaderText = "OutList($)", Width = 60 },
            new ColumnFormat { Name = "OutTotalList", HeaderText = "OutTotalList", Width = 0 },
            new ColumnFormat { Name = "OutMainPrice", HeaderText = "OutGross($)", Width = 70 },
            new ColumnFormat { Name = "OutMainTotalPrice", HeaderText = "T.OutGross($)", Width = 90 },
            new ColumnFormat { Name = "OutListMainDiscount", HeaderText = "OutDisc%", Width = 65 },
            new ColumnFormat { Name = "OutSecPrice", HeaderText = "OutGross(£)", Width = 0 },
            new ColumnFormat { Name = "OutSecTotalPrice", HeaderText = "T.OutGross(£)", Width = 0 },
            new ColumnFormat { Name = "ReturnWeight", HeaderText = "ReturnWeight", Width = 0 },
            new ColumnFormat { Name = "ReturnTotalCost", HeaderText = "ReturnTotalCost", Width = 0 },
            new ColumnFormat { Name = "ReturnTotalSale", HeaderText = "ReturnTotalSale", Width = 0 },
            new ColumnFormat { Name = "InvoicedWeight", HeaderText = "InvoicedWeight", Width = 0 },
            new ColumnFormat { Name = "InvoicedTotalCost", HeaderText = "InvoicedTotalCost", Width = 0 },
            new ColumnFormat { Name = "InvoicedTotalSale", HeaderText = "InvoicedTotalSale", Width = 0 },
            new ColumnFormat { Name = "DocPriceGross", HeaderText = "DocPriceGross", Width = 90 },
            new ColumnFormat { Name = "MainPriceGross", HeaderText = "MainPriceGross", Width = 95 },
            new ColumnFormat { Name = "SecPriceGross", HeaderText = "SecPriceGross", Width = 0 },
            new ColumnFormat { Name = "TotalDocPriceGross", HeaderText = "T. DocPriceGross", Width = 100 },
            new ColumnFormat { Name = "TotalMainPriceGross", HeaderText = "T.MainPriceGross", Width = 100 },
            new ColumnFormat { Name = "TotalSecPriceGross", HeaderText = "TotalSecPriceGross", Width = 0 },
            new ColumnFormat { Name = "DocPriceGrossWithTax", HeaderText = "DocPriceGrossWithTax", Width = 0 },
            new ColumnFormat { Name = "TotalDocPriceGrossWithTax", HeaderText = "TotalDocPriceGrossWithTax", Width = 0 },
            new ColumnFormat { Name = "DocPriceWithTax", HeaderText = "DocPriceWithTax", Width = 0 },
            new ColumnFormat { Name = "TotalDocPriceWithTax", HeaderText = "TotalDocPriceWithTax", Width = 0 },
            new ColumnFormat { Name = "DocTotalDiscountWithTax", HeaderText = "DocTotalDiscountWithTax", Width = 0 },
            new ColumnFormat { Name = "MarkupPercent", HeaderText = "MarkupPercent", Width = 0 },
            new ColumnFormat { Name = "DiscountPercent", HeaderText = "DiscountPercent", Width = 0 },
            new ColumnFormat { Name = "DocTotalDiscountAmount", HeaderText = "T.Discount", Width = 75 },
            new ColumnFormat { Name = "MainTotalDiscountAmount", HeaderText = "MainTotalDiscountAmount", Width = 0 },
            new ColumnFormat { Name = "SecTotalDiscountAmount", HeaderText = "SecTotalDiscountAmount", Width = 0 },
            new ColumnFormat { Name = "TrsUnionID", HeaderText = "TrsUnionID", Width = 0 },
            new ColumnFormat { Name = "SourceDocTypeID", HeaderText = "SourceDocTypeID", Width = 0 },
            new ColumnFormat { Name = "SourceDocTypeDesc", HeaderText = "SourceDocType", Width = 100 },
            new ColumnFormat { Name = "SourceDocID", HeaderText = "SourceDocID", Width = 80 },
            new ColumnFormat { Name = "SourceDocLine", HeaderText = "SourceDocLine", Width = 0 },
            new ColumnFormat { Name = "LastUpdate", HeaderText = "LastUpdate", Width = 0 },
            new ColumnFormat { Name = "UserID", HeaderText = "UserID", Width = 0 },
            new ColumnFormat { Name = "SourceDocCode", HeaderText = "SourceDocCode", Width = 100 }
        };

        public static List<ColumnFormat> WorkingLineColumnFormat = new List<ColumnFormat>
        {
            new ColumnFormat { Name = "DocHeaderID", HeaderText = "DocHeaderID", Width = 0 },
            new ColumnFormat { Name = "DocLineID", HeaderText = "DocLineID", Width = 0 },
            new ColumnFormat { Name = "DocTypeID", HeaderText = "DocTypeID", Width = 0 },
            new ColumnFormat { Name = "DocTypeDesc", HeaderText = "DocTypeDesc", Width = 0 },
            new ColumnFormat { Name = "DocID", HeaderText = "DocID", Width = 55 },
            new ColumnFormat { Name = "DocLine", HeaderText = "Line", Width = 35 },
            new ColumnFormat { Name = "DocLineStatus", HeaderText = "Status", Width = 45 },
            new ColumnFormat { Name = "LotID", HeaderText = "LotID", Width = 65 },
            new ColumnFormat { Name = "ParentLotID", HeaderText = "ParentLotID", Width = 70 },
            new ColumnFormat { Name = "ItemID", HeaderText = "ItemID", Width = 0 },
            new ColumnFormat { Name = "LotName", HeaderText = "LotName", Width = 80 },
            new ColumnFormat { Name = "ParcelOrStone", HeaderText = "ParcelOrStone", Width = 0 },
            new ColumnFormat { Name = "HoldingType", HeaderText = "HoldingType", Width = 0 },
            new ColumnFormat { Name = "CertificateID", HeaderText = "CertificateID", Width = 80 },
            new ColumnFormat { Name = "Shape", HeaderText = "Shape", Width = 70 },
            new ColumnFormat { Name = "Size", HeaderText = "Size", Width = 60 },
            new ColumnFormat { Name = "Color", HeaderText = "Color", Width = 50 },
            new ColumnFormat { Name = "Clarity", HeaderText = "Clarity", Width = 60 },
            new ColumnFormat { Name = "Quantity", HeaderText = "Quantity", Width = 0 },
            new ColumnFormat { Name = "Weight", HeaderText = "Weight", Width = 60 },
            new ColumnFormat { Name = "WeightLoss", HeaderText = "WeightLoss", Width = 0 },
            new ColumnFormat { Name = "Cost", HeaderText = "Cost($)", Width = 70 },
            new ColumnFormat { Name = "TotalCost", HeaderText = "T.Cost($)", Width = 70 },
            new ColumnFormat { Name = "SecCost", HeaderText = "Cost(£)", Width = 0 },
            new ColumnFormat { Name = "SecTotalCost", HeaderText = "T.Cost(£)", Width = 0 },
            new ColumnFormat { Name = "Sale", HeaderText = "Sale", Width = 0 },
            new ColumnFormat { Name = "TotalSale", HeaderText = "T.Sale", Width = 0 },
            new ColumnFormat { Name = "SecSale", HeaderText = "Sale(£)", Width = 0 },
            new ColumnFormat { Name = "SecTotalSale", HeaderText = "T.Sale(£)", Width = 0 },
            new ColumnFormat { Name = "Additional", HeaderText = "Additional", Width = 0 },
            new ColumnFormat { Name = "TotalAdditional", HeaderText = "T.Additional", Width = 0 },
            new ColumnFormat { Name = "MainPrice", HeaderText = "MainPrice", Width = 70 },
            new ColumnFormat { Name = "TotalMainPrice", HeaderText = "T.MainPrice", Width = 85 },
            new ColumnFormat { Name = "SecPrice", HeaderText = "GBP Price", Width = 85 },
            new ColumnFormat { Name = "TotalSecPrice", HeaderText = "T.GBP Price", Width = 95 },
            new ColumnFormat { Name = "DocPrice", HeaderText = "DocPrice", Width = 70 },
            new ColumnFormat { Name = "TotalDocPrice", HeaderText = "T.DocPrice", Width = 85 },
            new ColumnFormat { Name = "RateDocToMain", HeaderText = "RateDocToMain", Width = 0 },
            new ColumnFormat { Name = "RateDocToSec", HeaderText = "RateDocToSec", Width = 0 },
            new ColumnFormat { Name = "List", HeaderText = "List", Width = 0 },
            new ColumnFormat { Name = "TotalList", HeaderText = "TotalList", Width = 0 },
            new ColumnFormat { Name = "ListCostDiscount", HeaderText = "CostDisc%", Width = 70 },
            new ColumnFormat { Name = "ListSaleDiscount", HeaderText = "ListSaleDiscount", Width = 0 },
            new ColumnFormat { Name = "ListMainDiscount", HeaderText = "ListMainDiscount", Width = 0 },
            new ColumnFormat { Name = "Remark", HeaderText = "Remark", Width = 0 },
            new ColumnFormat { Name = "OutList", HeaderText = "OutList($)", Width = 60 },
            new ColumnFormat { Name = "OutTotalList", HeaderText = "OutTotalList", Width = 0 },
            new ColumnFormat { Name = "OutMainPrice", HeaderText = "OutGross($)", Width = 70 },
            new ColumnFormat { Name = "OutMainTotalPrice", HeaderText = "T.OutGross($)", Width = 90 },
            new ColumnFormat { Name = "OutListMainDiscount", HeaderText = "OutDisc%", Width = 65 },
            new ColumnFormat { Name = "OutSecPrice", HeaderText = "OutGross(£)", Width = 0 },
            new ColumnFormat { Name = "OutSecTotalPrice", HeaderText = "T.OutGross(£)", Width = 0 },
            new ColumnFormat { Name = "ReturnWeight", HeaderText = "ReturnWeight", Width = 0 },
            new ColumnFormat { Name = "ReturnTotalCost", HeaderText = "ReturnTotalCost", Width = 0 },
            new ColumnFormat { Name = "ReturnTotalSale", HeaderText = "ReturnTotalSale", Width = 0 },
            new ColumnFormat { Name = "InvoicedWeight", HeaderText = "InvoicedWeight", Width = 0 },
            new ColumnFormat { Name = "InvoicedTotalCost", HeaderText = "InvoicedTotalCost", Width = 0 },
            new ColumnFormat { Name = "InvoicedTotalSale", HeaderText = "InvoicedTotalSale", Width = 0 },
            new ColumnFormat { Name = "DocPriceGross", HeaderText = "DocPriceGross", Width = 90 },
            new ColumnFormat { Name = "MainPriceGross", HeaderText = "MainPriceGross", Width = 95 },
            new ColumnFormat { Name = "SecPriceGross", HeaderText = "SecPriceGross", Width = 0 },
            new ColumnFormat { Name = "TotalDocPriceGross", HeaderText = "T. DocPriceGross", Width = 100 },
            new ColumnFormat { Name = "TotalMainPriceGross", HeaderText = "T.MainPriceGross", Width = 100 },
            new ColumnFormat { Name = "TotalSecPriceGross", HeaderText = "TotalSecPriceGross", Width = 0 },
            new ColumnFormat { Name = "DocPriceGrossWithTax", HeaderText = "DocPriceGrossWithTax", Width = 0 },
            new ColumnFormat { Name = "TotalDocPriceGrossWithTax", HeaderText = "TotalDocPriceGrossWithTax", Width = 0 },
            new ColumnFormat { Name = "DocPriceWithTax", HeaderText = "DocPriceWithTax", Width = 0 },
            new ColumnFormat { Name = "TotalDocPriceWithTax", HeaderText = "TotalDocPriceWithTax", Width = 0 },
            new ColumnFormat { Name = "DocTotalDiscountWithTax", HeaderText = "DocTotalDiscountWithTax", Width = 0 },
            new ColumnFormat { Name = "MarkupPercent", HeaderText = "MarkupPercent", Width = 0 },
            new ColumnFormat { Name = "DiscountPercent", HeaderText = "DiscountPercent", Width = 0 },
            new ColumnFormat { Name = "DocTotalDiscountAmount", HeaderText = "T.Discount", Width = 75 },
            new ColumnFormat { Name = "MainTotalDiscountAmount", HeaderText = "MainTotalDiscountAmount", Width = 0 },
            new ColumnFormat { Name = "SecTotalDiscountAmount", HeaderText = "SecTotalDiscountAmount", Width = 0 },
            new ColumnFormat { Name = "TrsUnionID", HeaderText = "TrsUnionID", Width = 0 },
            new ColumnFormat { Name = "SourceDocTypeID", HeaderText = "SourceDocTypeID", Width = 0 },
            new ColumnFormat { Name = "SourceDocTypeDesc", HeaderText = "SourceDocType", Width = 100 },
            new ColumnFormat { Name = "SourceDocID", HeaderText = "SourceDocID", Width = 80 },
            new ColumnFormat { Name = "SourceDocLine", HeaderText = "SourceDocLine", Width = 0 },
            new ColumnFormat { Name = "LastUpdate", HeaderText = "LastUpdate", Width = 0 },
            new ColumnFormat { Name = "UserID", HeaderText = "UserID", Width = 0 },
            new ColumnFormat { Name = "SourceDocCode", HeaderText = "SourceDocCode", Width = 100 }
        };



    }
}
